#!/bin/bash
# barkeep - create entries based on a template for use with taverner

# Options
shopt -s nullglob

NAME=taverner
argv0=barkeep

prefix=${XDG_DATA_HOME:-$HOME/.local/share}/$NAME
bindir=$prefix/bin
coverdir=$prefix/covers
templatedir=$prefix/templates

readonly TMPDIR=/tmp

usage_mk() {
    cat <<'!'
Create a new menu entry.  Uses $EDITOR to complete the new entry.

    mk [-c <cover>] -t <template> <entry>
        -t      Select a template to base the new entry on.
        -c      Path or url to a cover image.  (Note: This is destructive)
        entry   The name for the new launcher script.

!
}

usage_ls() {
    cat <<!
List entries and templates.

    ls [-t]
        -t      List all available templates.

        If no arguments given this will list all entries.

!
}

usage_ed() {
    cat <<'!'
Edit the selected entry or template.  Only one entry may be edited per
invocation.

    ed [-t <template>] [-c <cover>] [entry]
        -t      Attempts to open the template with $EDITOR.
        -c      Replace the cover for entry, note that the entry is required
                for this operation.
        entry   Attempts to open the entry with $EDITOR.

    Issue: If -c is specified for an entry, it will both update the entries
           cover image but also offer to edit the entry as well.

!
}

usage_rm() {
    cat <<!
Remove selected entries and corresponding covers.  If no argument given,
attempt to remove all entires.

    rm [entry [entry]]
        entry   The chosen entry to remove.

!
}

usage() {
    cat <<'!'
Usage: barkeep [-h] [mk | ls | ed | rm]
    Each mode has an -h flag which produces a summary of its help section.

    -e      Preferred editor, uses $EDITOR if not set.

!

usage_mk
usage_ls
usage_ed
usage_rm

    cat <<!
Examples:
    # Creates an entry using the psx template called wipeout_3 using emacs
    # as the editor.
    taverner bk mk -e emacs -t psx wipeout_3

    # Removes both wipeout_3 and crash_bandicoot launchers along with any
    # cover images if found.
    taverner bk rm wipeout_3 crash_bandicoot
!
}

puts() {
    printf -- "$1\n" "${@:2}"
}

err() {
    puts "$argv0: $1" "${@:2}" >&2
}

confirm() {
    local msg=$1
    local -l reply

    read -rp "$msg [Y/n] " reply

    # If the reply is empty, assume Y
    [[ $reply == y || ! $reply ]]
}

handle_ls() {
    while (($#)); do
        case $1 in
            -t) ls_templates; exit ;;
            -h) usage_ls; exit ;;
            *)  err '%s: Unrecognised argument' "$1"; exit 1 ;;
        esac
        shift
    done

    ls_entries
}

ls_entries() {
    local entries

    entries=("$bindir"/*)

    if ((${#entries[@]})); then
        puts '%s' "${entries[@]##*/}"
    else
        err '%s: No entries found here' "$bindir"
    fi
}

ls_templates() {
    local templates

    templates=("$templatedir"/*)

    if ((${#templates[@]})); then
        puts '%s' "${templates[@]##*/}"
    else
        err '%s: No templates found here' "$templatedir"
    fi
}

handle_mk() {
    local entry cover template editor

    while (($#)); do
        case $1 in
            -c) shift; cover=$1 ;;
            -t) shift; template=$1 ;;
            -e) shift; editor=$1 ;;
            -h) usage_mk; exit ;;
            *) entry=$1
        esac
        shift
    done

    if [[ ! $entry ]]; then
        err 'An entry name is required'
        exit 1
    fi

    if [[ -e $bindir/$entry ]]; then
        err '%s: This entry already exists.  See %s ls -e' "$bindir"/"$entry" "$argv0"
        exit 1
    fi

    if [[ ! $template ]]; then
        err 'A template required.  See %s ls -t' "$argv0"
        exit 1
    fi

    if [[ ! -e $templatedir/$template ]]; then
        err '%s: Unable to find requested template' "$templatedir"/"$template"
        exit 1
    fi

    if [[ ! $cover ]]; then
        cover=$coverdir/placeholder
    else
        mk_cover "$entry" "$cover"
    fi

    mk_entry "$editor" "$bindir"/"$entry" "$templatedir"/"$template"
}

mk_entry() {
    local editor=$1
    local entry=$2
    local template=$3

    cp -vf -- "$template" "$entry"
    command "${editor:-${EDITOR:-vi}}" "$entry"
    chmod -c +x -- "$entry"
}

mk_cover() {
    local entry=$1
    local cover=$2

    if [[ $cover =~ [https?\|f]tp ]]; then
        if curl -#o "$TMPDIR"/barkeep_cover "$cover"; then
            cover=$TMPDIR/barkeep_cover
        else
            err '%s: Failed to download cover' "$cover"
            exit 1
        fi
    fi

    if [[ -e $cover ]]; then
        command gm mogrify -resize 368x527\! "$cover"
        mv -vf -- "$cover" "$coverdir"/"$entry"
    else
        err '%s: Unable to find cover' "$cover"
    fi
}

handle_rm() {
    local entry entries remove

    while (($#)); do
        case $1 in
            -h) usage_rm; exit ;;
            *)  entries+=($1)
        esac
        shift
    done

    if ! ((${#entries[@]})); then
        entries=("$bindir"/*)

        # As the proceeding removal code may not be dealing with absolute paths
        # if a user explicitly makes a selection we strip the bindir here to
        # keep it consistent with this assumption.
        entries=(${entries[@]##$bindir/})

        if ! ((${#entries[@]})); then
            err '%s: Nothing here to remove' "$bindir"
            exit 1
        fi
    fi

    puts 'Attempting to remove the following launchers:'
    puts '%s' "${entries[@]##$bindir/}"

    if ! confirm 'Continue?'; then
        puts 'Nothing removed'
        exit
    fi

    for entry in "${entries[@]}"; do
        if [[ -e $bindir/$entry ]]; then
            remove+=("$bindir"/"$entry")
        fi

        if [[ -e $coverdir/$entry ]]; then
            remove+=("$coverdir"/"$entry")
        fi
    done

    rm -vf -- "${remove[@]}"
}

handle_ed() {
    local entry cover template editor collated_files

    while (($#)); do
        case $1 in
            -c) shift; cover=$1 ;;
            -t) shift; template=$1 ;;
            -e) shift; editor=$1 ;;
            -h) usage_ed; exit ;;
            *) entry=$1
        esac
        shift
    done

    if [[ $entry && $cover ]]; then
        mk_cover "$entry" "$cover"
        exit
    fi

    if [[ $template && -e $templatedir/$template ]]; then
        collated_files+=("$templatedir"/"$template")
    fi

    if [[ $entry && -e $bindir/$entry ]]; then
        collated_files+=("$bindir"/"$entry")
    fi

    if ((${#collated_files[@]})); then
        command -- "${editor:-${EDITOR:-vi}}" "${collated_files[@]}"
    fi
}

barkeep()
{
mkdir -p "$bindir" "$coverdir" "$templatedir"

if ! (($#)); then
    err 'At least one argument is required'
    usage
    exit 1
fi

while (($#)); do
    case $1 in
        ed) shift; handle_ed "$@"
            exit ;;
        ls) shift; handle_ls "$@"
            exit ;;
        mk) shift; handle_mk "$@"
            exit ;;
        rm) shift; handle_rm "$@"
            exit ;;
        -h) usage
            exit ;;
        *)  err '%s: Unrecognised argument' "$1"
            usage
            exit 1
    esac
    shift
done

}


# taverner - generate dmenu for launchers and display cover images

shopt -s nullglob

argv0=taverner
prefix=${XDG_DATA_HOME:-$HOME/.local/share}/$NAME
bindir=$prefix/bin
coverdir=$prefix/covers
configdir="${XDG_CONFIG_HOME:-$HOME/.config}"/$NAME
config="$configdir"/menu


puts() {
    printf -- "$1\n" "${@:2}"
}

err() {
    puts "$argv0: $1" "${@:2}" >&2
}

title_in() {
    local title

    while read -r title; do
        if [[ $title =~ '# Title: '?(.*) ]]; then
            puts '%s' "${BASH_REMATCH[1]}"
            break
        fi
    done
}

generate_entry_data() {
    #global bindir coverdir
    local file filename title cover

    for file in "$bindir"/*; do
        if [[ -e $file ]]; then
            title=$(title_in < "$file")
        fi

        filename=${file##*/}

        # Use the filename if no title could be found.
        if [[ ! $title ]]; then
            title=$filename
        fi

        # If a matching cover image isn't found use a placeholder instead.
        if [[ -e $coverdir/$filename ]]; then
            cover=$coverdir/$filename
        else
            cover=$coverdir/placeholder
        fi

        puts '%s' "$title"
        puts '%s' "$file"
        puts '%s' "$cover"
    done
}

create_sorted_menu() {
    # global titles covers
    local key

    for key in "${!titles[@]}"; do
        puts "$key"
    done | sort
}

get_user_picks() {
    create_sorted_menu | ${launch_opts[@]}
}

launch() {
    local err
    local entry=$1

    if ! err=$(command -- "$entry"); then
        err '%s' "${err:-$entry}"
    fi
}

populate_arrays() {
    # global titles covers entry

    # Parse the list into two arrays.  We keep a consistent key so we can
    # access the correct corresonding information for both lookups.
    while {
        read -r title
        read -r entry
        read -r cover
    } do
        titles["$title"]="$entry"
        covers["$title"]="$cover"
    done
}

process_results() {
    # global titles
    local pick entry

    while read -r pick; do
        if [[ ${titles[$pick]} ]]; then
            entry="${titles[$pick]}"
        else
            err '%s: Cannot find associated launcher' "$pick"
            exit 1
        fi

        launch "$entry" &
    done
}

usage_taverner() { 
    cat <<!
Usage: taverner [bk] 
    
    bk [-h] [mk | ls | ed | rm]        
        Each mode has an -h flag which produces a summary of its help section.
        -e      Preferred editor, uses \$EDITOR if not set.

Run taverner with no arguments to show your app list using the command specified in $config
!
}

declare -A titles
declare -A covers

[[ $1 == 'bk' ]] && barkeep "${@:2}" && exit 0

[[ $1 == '-h' ]] && usage_taverner && exit 0
 
mkdir -p "$bindir" "$templatedir" "$configdir"
[[ ! -f $config ]] && touch $config

[[ ! -s $config ]] && err "Please specify a launch command in $config" && exit 1

read -r launch_opts < $config

populate_arrays < <(generate_entry_data)

results=$(get_user_picks)

if [[ $results ]]; then
    process_results <<< "$results"
fi
